### ISSUE TITLE
Add registry authentication tests

### ISSUE THREAD

**Issue by nu12** [nu12/dockerapi#4]
As of now we have no tests for registry authentication. Methods that need to be tested are:
* Image#push
* Image#build
* Image#create
* Image#distribution

Possible approaches: a) setup a local registry with authentication, b) stub the request/response.

**Comment by zarqman** [comment]
As asked in #3, and this might already be what you meant in (a) above, but what about creating an instance of [docker/registry](https://hub.docker.com/_/registry/) inside the being-tested docker daemon? You're already pushing images and creating containers there, so this is just another image + container in that regard. (This is different that requiring a pre-configured registry instance running external to the test suite.)

**Comment by nu12** [comment]
That's what I had in mind, but I thought I'd ask a second opinion. For testing the authentication itself this registry instance needs extra configuration such as htpasswd  and TLS ([reference](https://docs.docker.com/registry/deploying/#native-basic-auth)). I'm thinking about creating those files using `bin/setup` and then use them during tests.
